[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Misrab <faizullah.misrab@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num="0.2.1"
image="0.13.0"
